name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install cargo-audit
      run: cargo install --force cargo-audit
      
    - name: Run security audit
      run: cargo audit
      
    - name: Upload audit results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: security-audit-results
        path: |
          Cargo.lock
          audit-results.json